version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: kafka-poc-zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-poc-kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: ${KAFKA-TOPICS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-viewer:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-poc-viewer
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - "8085:8080"
